<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Shortener.Core/Shortener.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Polly.Core" />
  </ItemGroup>
</Project>
